### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cloud9350** [L7-MCPE/lav7#10]
I tried using this. :+1: 
1. This server is running on ARM Linux available?
2. Minecraft Version

**Comment by yale2a1** [comment]
1. Please see Link
http://cr0sh2k.tk/files/lav7/builds/2016-02-19/linux/arm/
2. Yes
Hmm.. by the way, ```builds/2016-2-19``` last build or ```builds/last``` last build I Don't Know

1. ARM 리눅스 지원합니다.
2. ```2-19```일에 빌드된게 최근인지 아니면 ```last```가 가장 최근에 빌드된건지 모르겠네요,,

**Comment by cloud9350** [comment]
@yale2a1 오오 님이 이 프로젝트를 할 줄은 몰랐네요 ㄷㄷ..
답변 감사합니다.
